"""
09_ssh.py — SSH access tests (inbound via wstunnel; outbound via ssh-agent)

Test A — Inbound SSH via wstunnel ProxyCommand:
  Prerequisites: wstunnel binary in PATH
  Skipped per-test if wstunnel not found.

Test B — Outbound SSH via devtainer's integrated ssh-agent:
  Prerequisites: docker CLI in PATH; harness_container_id known (or
    DOCKSIDE_TEST_CONTAINER_ID set); DOCKSIDE_TEST_SSH_SERVER set (default: git@github.com)
    and the testdev1 public key pre-authorised at that server.

The committed test-only Ed25519 keypairs are in:
  t/integration/config/ssh/testdev1_ed25519{,.pub}
  t/integration/config/ssh/testdev2_ed25519{,.pub}
"""

import os
import shutil
import subprocess
import sys
import tempfile
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'lib'))
from dockside_test import TestCase, APIError

PROFILE_NAME = '10-alpine'

_INTEGRATION_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
_SSH_DIR = os.path.join(_INTEGRATION_DIR, 'config', 'ssh')
_DEV1_KEY = os.path.join(_SSH_DIR, 'testdev1_ed25519')
_DEV2_KEY = os.path.join(_SSH_DIR, 'testdev2_ed25519')

SSH_CONTAINER = 'inttest-ssh-01'


def _wstunnel_available():
    return shutil.which('wstunnel') is not None


def _docker_available():
    try:
        r = subprocess.run(['docker', 'version'], capture_output=True, timeout=5)
        return r.returncode == 0
    except Exception:
        return False


def _build_proxy_command(uid_cookie_name, uid_cookie_value, wss_url, host_header=None):
    """
    Build a wstunnel ProxyCommand string matching the format generated by SSHInfo.vue:

      wstunnel --hostHeader=%n "--customHeaders=Cookie: <name>=<value>" \
               -L stdio:127.0.0.1:%p <wss_url>

    In local/harness mode, wss_url is wss://localhost:<port> and hostHeader is
    the ssh-<name>.<domain> hostname (passed via %n from ssh config's Host line).
    In remote mode, wss_url is wss://<host> and no explicit hostHeader needed
    (the Host header is already correct).
    """
    cookie_header = f'Cookie: {uid_cookie_name}={uid_cookie_value}'
    cmd = f'wstunnel --hostHeader=%n "--customHeaders={cookie_header}" -L stdio:127.0.0.1:%p {wss_url}'
    return cmd


def _write_ssh_config(tmpdir, host_pattern, proxy_command, hostname, identity_file):
    """Write a temporary SSH config file and return its path."""
    config_path = os.path.join(tmpdir, 'ssh_config')
    with open(config_path, 'w') as f:
        f.write(f'Host {host_pattern}\n')
        f.write(f'    ProxyCommand {proxy_command}\n')
        f.write(f'    Hostname {hostname}\n')
        f.write(f'    IdentityFile {identity_file}\n')
        f.write(f'    ForwardAgent yes\n')
        f.write(f'    StrictHostKeyChecking no\n')
        f.write(f'    UserKnownHostsFile /dev/null\n')
        f.write(f'    LogLevel ERROR\n')
    os.chmod(config_path, 0o600)
    return config_path


class SshTests(TestCase):
    """SSH access: inbound via wstunnel, outbound via integrated ssh-agent."""

    def setUp(self):
        super().setUp()
        self.register_cleanup(SSH_CONTAINER)

    def _ensure_ssh_container(self):
        """Create and start the SSH test container (testdev1 is owner)."""
        try:
            self.dev1.create(
                profile=PROFILE_NAME,
                name=SSH_CONTAINER,
            )
        except APIError as e:
            if 'already' not in str(e).lower() and 'exists' not in str(e).lower():
                raise
        data = self.dev1.get_container(SSH_CONTAINER)
        if data.get('status') != 1:
            self.dev1.start(SSH_CONTAINER, wait=True, timeout=120)
            time.sleep(2)

    def _get_ssh_host_pattern(self):
        """
        Return the SSH Host pattern and wss_url for the SSH config.
        For local/harness: 'ssh-inttest-ssh-01.<suffix>' and 'wss://localhost:<port>'
        For remote: 'ssh-inttest-ssh-01.<parent_fqdn_suffix>'
        """
        if self.dev1._connect_to:
            # local or harness mode
            import urllib.parse as _up
            parsed = _up.urlparse(self.dev1._server)
            host_parts = parsed.hostname.split('.', 1)
            suffix = host_parts[1] if len(host_parts) > 1 else parsed.hostname
            ssh_hostname = f'ssh-{SSH_CONTAINER}.{suffix}'
            port = parsed.port or 443
            wss_url = f'wss://localhost:{port}'
            return ssh_hostname, wss_url
        else:
            # remote mode
            data = self.dev1.get_container(SSH_CONTAINER)
            parent_fqdn = (data.get('data') or {}).get('parentFQDN') or data.get('parentFQDN') or ''
            ssh_hostname = f'ssh-{SSH_CONTAINER}{parent_fqdn}'
            parsed_server = __import__('urllib.parse').parse.urlparse(self.dev1._server)
            wss_url = f'wss://{parsed_server.hostname}'
            return ssh_hostname, wss_url

    # ── Test A: Inbound SSH via wstunnel ──────────────────────────────────────

    def test_01_owner_ssh_via_wstunnel(self):
        """testdev1 (owner) can SSH into their devtainer via wstunnel."""
        if not _wstunnel_available():
            self.skip('wstunnel not in PATH')
        if not os.path.isfile(_DEV1_KEY):
            self.skip(f'testdev1 key not found at {_DEV1_KEY}')

        self._ensure_ssh_container()

        uid_cookie = self.dev1.get_uid_cookie()
        if not uid_cookie:
            self.skip('Could not extract UID cookie from dev1 session')
        uid_name, uid_value = uid_cookie

        ssh_hostname, wss_url = self._get_ssh_host_pattern()
        proxy_cmd = _build_proxy_command(uid_name, uid_value, wss_url)

        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = _write_ssh_config(
                tmpdir,
                host_pattern=ssh_hostname,
                proxy_command=proxy_cmd,
                hostname=ssh_hostname,
                identity_file=_DEV1_KEY,
            )
            r = subprocess.run(
                ['ssh', '-F', config_path, ssh_hostname, 'echo', 'hello'],
                capture_output=True, text=True, timeout=30
            )
        self.assert_equal(r.stdout.strip(), 'hello',
                          f'SSH did not return hello; rc={r.returncode} '
                          f'stderr={r.stderr!r} stdout={r.stdout!r}')

    def test_02_ssh_proxy_denied_to_non_developer(self):
        """dev2 (not in developers) gets 410 from SSH router."""
        self._ensure_ssh_container()
        # Ensure dev2 is NOT in developers
        try:
            self.dev1.update(SSH_CONTAINER, developers='')
        except APIError:
            pass

        parent_fqdn = None if self.dev1._connect_to else self._get_parent_fqdn()
        try:
            code, _ = self.dev2.check_service(
                SSH_CONTAINER, router_prefix='ssh', parent_fqdn=parent_fqdn
            )
            self.assert_http_status(code, 410,
                                    f'dev2 got {code} for SSH when not in developers')
        except APIError as e:
            self.skip(f'Could not check SSH service: {e}')

    def _get_parent_fqdn(self):
        data = self.dev1.get_container(SSH_CONTAINER)
        return (data.get('data') or {}).get('parentFQDN') or data.get('parentFQDN')

    def test_03_add_dev2_and_ssh_connects(self):
        """After adding testdev2 as developer, they can SSH in with their key."""
        if not _wstunnel_available():
            self.skip('wstunnel not in PATH')
        if not os.path.isfile(_DEV2_KEY):
            self.skip(f'testdev2 key not found at {_DEV2_KEY}')

        self._ensure_ssh_container()

        # Add testdev2 as developer (owner testdev1 does this)
        self.dev1.update(SSH_CONTAINER, developers='testdev2')
        # Dockside regenerates authorized_keys; give it a moment
        time.sleep(2)

        uid_cookie = self.dev2.get_uid_cookie()
        if not uid_cookie:
            self.skip('Could not extract UID cookie from dev2 session')
        uid_name, uid_value = uid_cookie

        ssh_hostname, wss_url = self._get_ssh_host_pattern()
        proxy_cmd = _build_proxy_command(uid_name, uid_value, wss_url)

        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = _write_ssh_config(
                tmpdir,
                host_pattern=ssh_hostname,
                proxy_command=proxy_cmd,
                hostname=ssh_hostname,
                identity_file=_DEV2_KEY,
            )
            r = subprocess.run(
                ['ssh', '-F', config_path, ssh_hostname, 'echo', 'hello'],
                capture_output=True, text=True, timeout=30
            )
        self.assert_equal(r.stdout.strip(), 'hello',
                          f'dev2 SSH failed; rc={r.returncode} '
                          f'stderr={r.stderr!r} stdout={r.stdout!r}')

    def test_04_remove_dev2_and_ssh_denied(self):
        """After removing testdev2 from developers, SSH proxy returns 410."""
        self._ensure_ssh_container()
        self.dev1.update(SSH_CONTAINER, developers='testdev2')
        self.dev1.update(SSH_CONTAINER, developers='')
        time.sleep(1)

        parent_fqdn = None if self.dev1._connect_to else self._get_parent_fqdn()
        try:
            code, _ = self.dev2.check_service(
                SSH_CONTAINER, router_prefix='ssh', parent_fqdn=parent_fqdn
            )
            self.assert_http_status(code, 410,
                                    f'dev2 got {code} after being removed from developers')
        except APIError as e:
            self.skip(f'Could not check SSH service: {e}')

    # ── Test B: Outbound SSH via integrated ssh-agent ─────────────────────────

    def test_05_outgoing_ssh_via_integrated_agent(self):
        """
        Use the devtainer's integrated ssh-agent to SSH outward.
        Requires: docker CLI, container ID, DOCKSIDE_TEST_SSH_SERVER.
        """
        if not _docker_available():
            self.skip('docker CLI not available')

        container_id = (
            self.harness_container_id
            or os.environ.get('DOCKSIDE_TEST_CONTAINER_ID', '').strip()
        )
        if not container_id:
            self.skip('No Dockside container ID available (set DOCKSIDE_TEST_CONTAINER_ID)')

        ssh_server = os.environ.get('DOCKSIDE_TEST_SSH_SERVER', 'git@github.com').strip()

        self._ensure_ssh_container()

        # Find the devtainer's container ID
        data = self.dev1.get_container(SSH_CONTAINER)
        devtainer_id = (data.get('data') or {}).get('id') or data.get('containerId')
        if not devtainer_id:
            self.skip('Could not determine devtainer container ID')

        # Find SSH_AUTH_SOCK inside the devtainer
        r = subprocess.run(
            ['docker', 'exec', devtainer_id, 'bash', '-c',
             'ls /tmp/ssh-*/agent.* 2>/dev/null | head -1'],
            capture_output=True, text=True, timeout=10
        )
        agent_sock = r.stdout.strip()
        if not agent_sock:
            self.skip('No ssh-agent socket found in devtainer (IDE not started?)')

        # SSH outward via the agent
        r = subprocess.run(
            ['docker', 'exec', '-e', f'SSH_AUTH_SOCK={agent_sock}',
             devtainer_id, 'ssh', '-T', '-o', 'StrictHostKeyChecking=no',
             ssh_server],
            capture_output=True, text=True, timeout=30
        )
        output = (r.stdout + r.stderr).lower()
        if 'github.com' in ssh_server:
            self.assert_true(
                'successfully authenticated' in output,
                f'Expected "successfully authenticated" in output; got: {output[:200]!r}'
            )
        else:
            # For a custom server, expect exit 0 or a known success message
            self.assert_true(
                r.returncode == 0 or 'authenticated' in output or 'welcome' in output,
                f'Outgoing SSH failed; rc={r.returncode} output={output[:200]!r}'
            )
