"""
Shared helpers for SSH integration tests.
"""

import os
import shutil
import subprocess
import tempfile
import urllib.parse

from dockside_test import APIError

_INTEGRATION_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
_SSH_DIR = os.path.join(_INTEGRATION_DIR, 'config', 'ssh')
_DEV1_KEY = os.path.join(_SSH_DIR, 'testdev1_ed25519')
_DEV2_KEY = os.path.join(_SSH_DIR, 'testdev2_ed25519')

_BASE_SSH_CONTAINER = 'inttest-ssh-01'


def wstunnel_available():
    return shutil.which('wstunnel') is not None


def docker_available():
    try:
        result = subprocess.run(['docker', 'version'], capture_output=True, timeout=5)
        return result.returncode == 0
    except Exception:
        return False


def build_proxy_command(uid_cookie_name, uid_cookie_value, wss_url):
    """
    Build a wstunnel ProxyCommand string matching the format generated by SSHInfo.vue.
    """
    cookie_header = f'Cookie: {uid_cookie_name}={uid_cookie_value}'
    return (
        f'wstunnel --hostHeader=%n "--customHeaders={cookie_header}" '
        f'-L stdio:127.0.0.1:%p {wss_url}'
    )


def write_ssh_config(tmpdir, host_pattern, proxy_command, hostname, identity_file):
    """Write a temporary SSH config file and return its path."""
    config_path = os.path.join(tmpdir, 'ssh_config')
    with open(config_path, 'w') as fh:
        fh.write(f'Host {host_pattern}\n')
        fh.write(f'    ProxyCommand {proxy_command}\n')
        fh.write(f'    Hostname {hostname}\n')
        fh.write(f'    IdentityFile {identity_file}\n')
        fh.write('    ForwardAgent yes\n')
        fh.write('    StrictHostKeyChecking no\n')
        fh.write('    UserKnownHostsFile /dev/null\n')
        fh.write('    LogLevel ERROR\n')
    os.chmod(config_path, 0o600)
    return config_path


class SshTestMixin:
    """Common container and routing helpers for SSH tests."""

    @classmethod
    def setUpClass(cls):
        cls.SSH_CONTAINER = cls._sfx(_BASE_SSH_CONTAINER)

    @classmethod
    def tearDownClass(cls):
        for fn in (
            lambda: cls.dev1.stop(cls.SSH_CONTAINER, wait=False),
            lambda: cls.dev1.remove(cls.SSH_CONTAINER, wait=False),
        ):
            try:
                fn()
            except Exception:
                pass

    def _ensure_ssh_container(self):
        """Create and start the SSH test container (dev1 is owner)."""
        try:
            self.dev1.create(
                profile=self.test_profile_alpine,
                name=self.SSH_CONTAINER,
            )
        except APIError as exc:
            if 'already' not in str(exc).lower() and 'exists' not in str(exc).lower():
                raise
        data = self.dev1.get_container(self.SSH_CONTAINER)
        if data.get('status') != 1:
            self.dev1.start(self.SSH_CONTAINER, wait=True, timeout=120)
        self.wait_running(self.dev1, self.SSH_CONTAINER, timeout=20)

    def _get_ssh_host_pattern(self):
        """
        Return (ssh_hostname, wss_url) for the SSH config.

        local/harness: ssh_hostname = ssh-<name>.<domain-suffix>
                       wss_url      = wss://localhost:<port>
        remote:        ssh_hostname = ssh-<name><parentFQDN>
                       wss_url      = wss://<server-hostname>
        """
        server_hostname = urllib.parse.urlparse(self.dev1._server).hostname or ''

        if self.dev1._connect_to:
            parts = server_hostname.split('.', 1)
            domain_sfx = parts[1] if len(parts) > 1 else server_hostname
            ssh_hostname = f'ssh-{self.SSH_CONTAINER}.{domain_sfx}'
            connect_to = self.dev1._connect_to
            if ':' in connect_to:
                _, _, port_str = connect_to.rpartition(':')
                port = int(port_str)
            else:
                port = 443
            wss_url = f'wss://localhost:{port}'
        else:
            data = self.dev1.get_container(self.SSH_CONTAINER)
            parent_fqdn = (data.get('data') or {}).get('parentFQDN') or data.get('parentFQDN') or ''
            ssh_hostname = f'ssh-{self.SSH_CONTAINER}{parent_fqdn}'
            wss_url = f'wss://{server_hostname}'

        return ssh_hostname, wss_url

    def _get_parent_fqdn(self):
        data = self.dev1.get_container(self.SSH_CONTAINER)
        return (data.get('data') or {}).get('parentFQDN') or data.get('parentFQDN')

    def _ssh_route_status(self, client):
        """Return the SSH router status code, or None if not yet reachable."""
        parent_fqdn = None if client._connect_to else self._get_parent_fqdn()
        try:
            code, _ = client.check_service(
                self.SSH_CONTAINER, router_prefix='ssh', parent_fqdn=parent_fqdn
            )
        except APIError:
            return None
        return code

    def _wait_ssh_route_status(self, client, expected_code, timeout=20):
        """Poll the SSH router until it returns expected_code."""
        self.wait_until(
            lambda: self._ssh_route_status(client) == expected_code,
            timeout=timeout,
            interval=1,
            timeout_msg=f'SSH route did not return {expected_code}',
        )

    def _wait_ssh_route_accessible(self, client, timeout=20):
        """Poll until the SSH router stops returning the denied code."""
        self.wait_until(
            lambda: (lambda code: code is not None and code != 410)(self._ssh_route_status(client)),
            timeout=timeout,
            interval=1,
            timeout_msg='SSH route did not become accessible',
        )

