# global settings
title: "Dockside - develop in clones of your production environment"
description: "A dev and staging environment in one - Dockside lets dev teams code from anywhere in clones of their production environment and share and stage their work online for stakeholders."
permalink: "/stories/:title"
url: https://dockside.io
relative_permalinks: false

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules"]
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
