# global settings
title: "Dockside - Develop in containers using production environments"
description: "Provision lightweight access-controlled IDEs, staging environments and sandboxes - aka ‘devtainers’ - on local machine, on-premises raw metal or VM, or in the cloud."
permalink: "/stories/:title"
url: https://dockside.io
relative_permalinks: false

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules"]
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
