#!/bin/sh

set -e

export BUNDLE_PATH=/home/dockside/.gems
mkdir -p $BUNDLE_PATH
bundle install

# Patch to pathutil to support Ruby >= 3.0.0
curl https://github.com/envygeeks/pathutil/commit/3451a10c362fc867b20c7e471a551b31c40a0246.patch | patch -p1 -f -d $(dirname $(find $BUNDLE_PATH -name pathutil.rb))/..
