services:
  dockside:
    container_name: ${NAME:-dockside}
    image: ${IMAGE:-newsnowlabs/dockside:test}
    restart: unless-stopped
    attach: false
    command: ["--ssl-selfsupplied", "--ssl-zone", "staging.newsnow.co.uk", "--lxcfs-available"]
    ports:
      - "${HTTPS_PORT:-443}:443"
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ${HOME}/.dockside:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - dockside-hostdata:/opt/dockside/host
      - /home/newsnow/dehydrated+wildcards/certs/staging.newsnow.co.uk/:/data/certs
    security_opt:
      - apparmor:unconfined
    networks:
      dockside:
        mac_address: "02:00:00:00:00:01"
        ipv4_address: 172.15.0.2
        gw_priority: 1000
      ds-priv:
        mac_address: "02:00:00:00:00:01"
        ipv4_address: 172.18.0.2
        gw_priority: 100
      ds-clone:
        mac_address: "02:00:00:00:00:01"
        ipv4_address: 172.17.0.2
        gw_priority: 101
      ds-prod:
        mac_address: "02:00:00:00:00:01"
        ipv4_address: 172.16.0.2
        gw_priority: 102

volumes:
  dockside-hostdata:

networks:
  dockside:
    name: "${DS_MAIN_DNET:-ds-main}"
    driver: bridge
    ipam:
      config:
        - subnet: "${DS_MAIN_SUBNET:-172.15.0.0/16}"
          gateway: "${DS_MAIN_GATEWAY:-172.15.0.1}"
    driver_opts:
      com.docker.network.bridge.name: "${DS_MAIN_DEV:-ds-main}"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"

  ds-priv:
    name: "${DS_PRIV_DNET:-ds-priv}"
    driver: bridge
    ipam:
      config:
        - subnet: "${DS_PRIV_SUBNET:-172.18.0.0/16}"
          gateway: "${DS_PRIV_GATEWAY:-172.18.0.1}"
    driver_opts:
      com.docker.network.bridge.name: "${DS_PRIV_DEV:-ds-priv}"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"

  ds-prod:
    name: "${DS_PROD_DNET:-ds-prod}"
    driver: bridge
    ipam:
      config:
        - subnet: "${DS_PROD_SUBNET:-172.16.0.0/16}"
          gateway: "${DS_PROD_GATEWAY:-172.16.0.1}"
    driver_opts:
      com.docker.network.bridge.name: "${DS_PROD_DEV:-ds-prod}"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"

  ds-clone:
    name: "${DS_CLONE_DNET:-ds-clone}"
    driver: bridge
    ipam:
      config:
        - subnet: "${DS_CLONE_SUBNET:-172.17.0.0/16}"
          gateway: "${DS_CLONE_GATEWAY:-172.17.0.1}"
    driver_opts:
      com.docker.network.bridge.name: "${DS_CLONE_DEV:-ds-clone}"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"