#!/bin/bash

cgroupfs_mount() {
	# see also https://github.com/tianon/cgroupfs-mount/blob/master/cgroupfs-mount
	if grep -v '^#' /etc/fstab | grep -q cgroup \
		|| [ ! -e /proc/cgroups ] \
		|| [ ! -d /sys/fs/cgroup ]; then
		return
	fi
	if ! mountpoint -q /sys/fs/cgroup; then
		mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
	fi
   if [ "$(mountpoint -d /sys/fs/cgroup)" == "0:26" ]; then
      # If cgroups v1, '0:26' (and not cgroups v2, '0:27')
      (
         cd /sys/fs/cgroup
         for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
            mkdir -p $sys
            if ! mountpoint -q $sys; then
               if ! mount -n -t cgroup -o $sys cgroup $sys; then
                  rmdir $sys || true
               fi
            fi
         done
      )
   fi
}

cgroupfs_mount

ulimit -u unlimited

mkdir -p /var/log/docker
DOCKER_LOGFILE=/var/log/docker/docker.log

exec >"$DOCKER_LOGFILE"
exec 2>"$DOCKER_LOGFILE"
exec /usr/bin/dockerd