name: Build

# Controls when the workflow will run
on:
  workflow_dispatch: # Allow for running this manually.
  push:
    branches:
      - 'multiarch'
    tags:
      - 'v*.*.*'
      - 'test'

# permissions are needed if pushing to ghcr.io
permissions: 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: dockside
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            newsnowlabs/dockside
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args:
            - OPT_PATH=/opt/dockside
            - THEIA_VERSION=1.27.0
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.dockside.outputs.tags }}
          labels: ${{ steps.dockside.outputs.labels }}
