name: Build

# Controls when the workflow will run
on:
  workflow_dispatch: # Allow for running this manually.
  push:
    tags:
      - 'v*.*.*'
      - 'pre-v*.*.*'
      - 'test*'

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write
  id-token: write # allow issuing OIDC tokens for this workflow run
  contents: read  # allow at least reading the repo contents, add other permissions if necessary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
      # Set up Depot (https://depot.dev/) for building Docker images faster and smarter, in the cloud
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      # Login to Docker Hub
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Setup Docker metadata
      - name: Docker meta
        id: dockside
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            newsnowlabs/dockside
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      # Build using Depot (https://depot.dev/) for building Docker images faster and smarter, in the cloud
      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          project: mmq8p477cl
          context: .
          build-args: |
            OPT_PATH=/opt/dockside
            THEIA_VERSION=1.27.0
          platforms: linux/arm/v7,linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.dockside.outputs.tags }}
          labels: ${{ steps.dockside.outputs.labels }}
